const data = [
  {
    adult: false,
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    popularity: 4456.007,
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    video: false,
    vote_average: 7.9,
    vote_count: 2684,
  },
  {
    adult: false,
    backdrop_path: "/2klQ1z1fcHGgQPevbEQdkCnzyuS.jpg",
    genre_ids: [16, 10751, 12, 14, 35],
    id: 502356,
    original_language: "en",
    original_title: "The Super Mario Bros. Movie",
    overview:
      "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
    popularity: 3392.2,
    poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    release_date: "2023-04-05",
    title: "The Super Mario Bros. Movie",
    video: false,
    vote_average: 7.8,
    vote_count: 4327,
  },
  {
    adult: false,
    backdrop_path: "/2I5eBh98Q4aPq8WdQrHdTC8ARhY.jpg",
    genre_ids: [28, 12, 16, 878],
    id: 569094,
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    popularity: 2921.844,
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    release_date: "2023-05-31",
    title: "Spider-Man: Across the Spider-Verse",
    video: false,
    vote_average: 8.8,
    vote_count: 739,
  },
  {
    adult: false,
    backdrop_path: "/4t0oBFrJyweYPt0hocW6RUa0b6H.jpg",
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 2334.66,
    poster_path: "/1E5baAaEse26fej7uHcjOgEE2t2.jpg",
    release_date: "2023-05-17",
    title: "Fast X",
    video: false,
    vote_average: 7.1,
    vote_count: 854,
  },
  {
    adult: false,
    backdrop_path: "/1IM8i8HiomFC4y6NRyBuDrHJWg3.jpg",
    genre_ids: [12, 10751, 14, 10749],
    id: 447277,
    original_language: "en",
    original_title: "The Little Mermaid",
    overview:
      "The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.",
    popularity: 1482.026,
    poster_path: "/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
    release_date: "2023-05-18",
    title: "The Little Mermaid",
    video: false,
    vote_average: 6.1,
    vote_count: 510,
  },
  {
    adult: false,
    backdrop_path: "/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg",
    genre_ids: [28, 12, 878],
    id: 640146,
    original_language: "en",
    original_title: "Ant-Man and the Wasp: Quantumania",
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    popularity: 1166.051,
    poster_path: "/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
    release_date: "2023-02-15",
    title: "Ant-Man and the Wasp: Quantumania",
    video: false,
    vote_average: 6.5,
    vote_count: 3145,
  },
  {
    adult: false,
    backdrop_path: "/aAgGrfBwna1nO4M2USxwFgK5O0t.jpg",
    genre_ids: [53, 27],
    id: 713704,
    original_language: "en",
    original_title: "Evil Dead Rise",
    overview:
      "Three siblings find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
    popularity: 1218.785,
    poster_path: "/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg",
    release_date: "2023-04-12",
    title: "Evil Dead Rise",
    video: false,
    vote_average: 7.1,
    vote_count: 1528,
  },
  {
    adult: false,
    backdrop_path: "/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg",
    genre_ids: [27, 53],
    id: 890771,
    original_language: "en",
    original_title: "The Black Demon",
    overview:
      "Oilman Paul Sturges' idyllic family vacation turns into a nightmare when they encounter a ferocious megalodon shark that will stop at nothing to protect its territory. Stranded and under constant attack, Paul and his family must somehow find a way to get his family back to shore alive before it strikes again in this epic battle between humans and nature.",
    popularity: 1428.574,
    poster_path: "/uiFcFIjig0YwyNmhoxkxtAAVIL2.jpg",
    release_date: "2023-04-26",
    title: "The Black Demon",
    video: false,
    vote_average: 6.4,
    vote_count: 91,
  },
  {
    adult: false,
    backdrop_path: "/94TIUEhuwv8PhdIADEvSuwPljS5.jpg",
    genre_ids: [28, 10752],
    id: 840326,
    original_language: "fi",
    original_title: "Sisu",
    overview:
      "Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.",
    popularity: 1059.76,
    poster_path: "/ygO9lowFMXWymATCrhoQXd6gCEh.jpg",
    release_date: "2023-01-27",
    title: "Sisu",
    video: false,
    vote_average: 7.4,
    vote_count: 605,
  },
  {
    adult: false,
    backdrop_path: "/suw8eyL3YwE4wfzPQ0cLR02k0Gh.jpg",
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    popularity: 984.223,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    video: false,
    vote_average: 7.7,
    vote_count: 8335,
  },
  {
    adult: false,
    backdrop_path: "/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
    genre_ids: [878, 12, 28],
    id: 447365,
    original_language: "en",
    original_title: "Guardians of the Galaxy Vol. 3",
    overview:
      "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    popularity: 1080.396,
    poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    release_date: "2023-05-03",
    title: "Guardians of the Galaxy Vol. 3",
    video: false,
    vote_average: 8.1,
    vote_count: 1839,
  },
  {
    adult: false,
    backdrop_path: "/eTvN54pd83TrSEOz6wbsXEJktCV.jpg",
    genre_ids: [10752, 28, 53],
    id: 882569,
    original_language: "en",
    original_title: "Guy Ritchie's The Covenant",
    overview:
      "During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.",
    popularity: 1056.899,
    poster_path: "/kVG8zFFYrpyYLoHChuEeOGAd6Ru.jpg",
    release_date: "2023-04-19",
    title: "Guy Ritchie's The Covenant",
    video: false,
    vote_average: 7.6,
    vote_count: 465,
  },
  {
    adult: false,
    backdrop_path: "/35slSk2fwFGDK8pZnPprOFKWxhV.jpg",
    genre_ids: [35, 28, 14],
    id: 594767,
    original_language: "en",
    original_title: "Shazam! Fury of the Gods",
    overview:
      'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    popularity: 815.774,
    poster_path: "/A3ZbZsmsvNGdprRi2lKgGEeVLEH.jpg",
    release_date: "2023-03-15",
    title: "Shazam! Fury of the Gods",
    video: false,
    vote_average: 6.7,
    vote_count: 1887,
  },
  {
    adult: false,
    backdrop_path: "/gFiPQZh6W2qEVKYnAQjtq66qJqI.jpg",
    genre_ids: [53, 18, 28],
    id: 1107872,
    original_language: "pl",
    original_title: "Dzień Matki",
    overview:
      "Nina, a former NATO special operations agent living in hiding, has to use all her deadly skills to rescue her son who has been kidnapped by ruthless gangsters. Finding Max is a double opportunity for her. A chance to feel the adrenaline rush again, and an opportunity to get back into the life of the son she had to abandon years ago.",
    popularity: 973.105,
    poster_path: "/wws9Z90DdZ7D0n3gdzFSZ6cntJi.jpg",
    release_date: "2023-05-24",
    title: "Mother's Day",
    video: false,
    vote_average: 5.9,
    vote_count: 83,
  },
  {
    adult: false,
    backdrop_path: "/jAmmb9RApuRckDJtYWeOgBUgQyG.jpg",
    genre_ids: [16, 28, 14, 878],
    id: 893712,
    original_language: "ja",
    original_title:
      "劇場版 ソードアート・オンライン -プログレッシブ- 冥き夕闇のスケルツォ",
    overview:
      'Over a month has passed since 10,000 users were trapped inside the "Sword Art Online" world. Asuna, who cleared the first floor of the floating iron castle of Aincrad, joined up with Kirito and continued her journey to reach the top floor. With the support of female Information Broker Argo, clearing the floors seemed to be progressing smoothly, but conflict erupts between two major guilds who should be working together – the top player groups ALS (the Aincrad Liberation Squad) and DKB (the Dragon Knights Brigade). And meanwhile, behind the scenes exists a mysterious figure pulling the strings…',
    popularity: 870.912,
    poster_path: "/2lEyzOq6ILNgBpLLpTRckQhbNNt.jpg",
    release_date: "2022-10-22",
    title: "Sword Art Online the Movie -Progressive- Scherzo of Deep Night",
    video: false,
    vote_average: 7.8,
    vote_count: 60,
  },
  {
    adult: false,
    backdrop_path: "/T5xXoFqyc9jNXZIbH4Sw0jwWjw.jpg",
    genre_ids: [28, 80, 53, 9648],
    id: 605886,
    original_language: "en",
    original_title: "To Catch a Killer",
    overview:
      "Baltimore. New Year's Eve. A talented but troubled police officer is recruited by the FBI's chief investigator to help profile and track down a mass murderer.",
    popularity: 777.129,
    poster_path: "/mFp3l4lZg1NSEsyxKrdi0rNK8r1.jpg",
    release_date: "2023-04-06",
    title: "To Catch a Killer",
    video: false,
    vote_average: 6.9,
    vote_count: 239,
  },
  {
    adult: false,
    backdrop_path: "/A5UrOppVdGHPfz1QnrOOdHV7G5A.jpg",
    genre_ids: [28, 53, 27],
    id: 799379,
    original_language: "ko",
    original_title: "늑대사냥",
    overview:
      "While under heavily armed guard, the dangerous convicts aboard a cargo ship unite in a coordinated escape attempt that soon escalates into a bloody, all-out riot. But as the fugitives continue their brutal campaign of terror, they soon discover that not even the most vicious among them is safe from the horror they unknowingly unleashed from the darkness below deck.",
    popularity: 808.577,
    poster_path: "/dniWicB6fa7NvpGbguxWlNPMc5f.jpg",
    release_date: "2022-09-21",
    title: "Project Wolf Hunting",
    video: false,
    vote_average: 6.4,
    vote_count: 151,
  },
  {
    adult: false,
    backdrop_path: "/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg",
    genre_ids: [27, 53],
    id: 758323,
    original_language: "en",
    original_title: "The Pope's Exorcist",
    overview:
      "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    popularity: 849.755,
    poster_path: "/gNPqcv1tAifbN7PRNgqpzY8sEJZ.jpg",
    release_date: "2023-04-05",
    title: "The Pope's Exorcist",
    video: false,
    vote_average: 7.3,
    vote_count: 1324,
  },
  {
    adult: false,
    backdrop_path: "/mfPfFVhpnGp8bG4IUoBJPUs2xKj.jpg",
    genre_ids: [878, 28, 12, 10751],
    id: 620705,
    original_language: "en",
    original_title: "Crater",
    overview:
      "After the death of his father, a boy growing up on a lunar mining colony takes a trip to explore a legendary crater, along with his four best friends, prior to being permanently relocated to another planet.",
    popularity: 560.605,
    poster_path: "/n8ZpMwYT02XjpQHpSxn1eJw5Zpz.jpg",
    release_date: "2023-05-12",
    title: "Crater",
    video: false,
    vote_average: 6.7,
    vote_count: 150,
  },
  {
    adult: false,
    backdrop_path: "/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg",
    genre_ids: [28, 53],
    id: 552688,
    original_language: "en",
    original_title: "The Mother",
    overview:
      "A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.",
    popularity: 770.278,
    poster_path: "/vnRthEZz16Q9VWcP5homkHxyHoy.jpg",
    release_date: "2023-05-04",
    title: "The Mother",
    video: false,
    vote_average: 6.8,
    vote_count: 714,
  },
];
